"""empty message

Revision ID: 83b1497a1725
Revises: 98b18e19787b
Create Date: 2025-11-30 15:04:15.831994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b1497a1725'
down_revision = '98b18e19787b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('coupon_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_zone_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_fee', sa.Float(), nullable=True))
        batch_op.create_foreign_key('delivery_ref', 'delivery_zone', ['delivery_zone_id'], ['id'])
        batch_op.create_foreign_key('uq_coupon_ref', 'coupon', ['coupon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('delivery_ref', type_='foreignkey')
        batch_op.drop_constraint('uq_coupon_ref', type_='foreignkey')
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('delivery_zone_id')
        batch_op.drop_column('coupon_id')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('subtotal_amount')

    # ### end Alembic commands ###
