"""empty message

Revision ID: 98b18e19787b
Revises: 1c339205290a
Create Date: 2025-11-30 14:48:03.305660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b18e19787b'
down_revision = '1c339205290a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_zone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eta', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_zone', schema=None) as batch_op:
        batch_op.drop_column('eta')

    # ### end Alembic commands ###
